# Generated by Django 3.1.3 on 2021-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_recipe',
            name='menu',
            field=models.CharField(choices=[('한식', '한식'), ('중식', '중식'), ('양식', '양식'), ('일식', '일식')], max_length=10),
        ),
    ]
