# Generated by Django 3.1.3 on 2021-05-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('menu', models.CharField(choices=[('한식', '한식'), ('중식', '중식'), ('양식', '양식'), ('일식', '일식')], max_length=10)),
                ('material', models.TextField()),
                ('how_Make', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='share_recipe',
        ),
    ]
