# Generated by Django 3.1.3 on 2021-05-09 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_recipe', '0002_auto_20210508_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_recipe',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
