# Generated by Django 3.1.3 on 2021-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_recipe', '0002_auto_20210507_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='share_recipe',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
