# Generated by Django 3.1.3 on 2021-05-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_recipe', '0006_share_recipe_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share_recipe',
            name='like_count',
        ),
    ]
