# Generated by Django 3.1.3 on 2021-05-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_recipe', '0008_auto_20210524_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='post',
            new_name='recipe',
        ),
    ]
