# Generated by Django 3.1.3 on 2021-05-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_recipe', '0009_auto_20210524_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share_recipe',
            name='image',
        ),
    ]
